### ISSUE TITLE
Schedule episode page publishing

### ISSUE THREAD

**Issue by bencodezen** [enjoythevue/website#138]
The problem we have is that we often have to publish our web page for the episode before the episode even goes live. Not great since this means there's an overlay where we're either too early or too late.

Do you know if there's a way for us to maybe schedule a PR merge with GitHub Actions or something?

**Comment by znck** [comment]
I don't understand the current process, why do we have to publish often? Do we need some time-sensitive data at build time? Github actions support cron-based scheduling, should I configure it?

**Comment by elizabethfinedev** [comment]
Hi Rahul! That might be helpful. The issue is that we usually put our episodes out Monday really early (like 6AM eastern time I believe) and we currently manually publish each episode page on our website.  So we end up publishing the episode late on Sunday night.  This isnt ideal for a couple reasons:
1) The episode page gets published on Sunday night before the episode is _actually out_ on Monday morning.
2) It leads to kind of a stressful rush of someone having to put together the episode late on a Sunday night.
